services:
  - type: web
    name: fastapi-mongodb-crud
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: MONGODB_URL
        sync: false
      - key: DATABASE_NAME
        value: crud_app
      - key: ENVIRONMENT
        value: production
